config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resources :superheroes
    root 'superheroes#index'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/superhero.rb
class Superhero < ApplicationRecord
  extend Mobility
  translates :nemesis, :gadget, :name, :description
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Locale
end

app/controllers/concerns/locale.rb
module Locale
  extend ActiveSupport::Concern

  private

  def extract_locale(attr = :locale)
    parsed_locale = params[attr]
    I18n.available_locales.map(&:to_s).include?(parsed_locale) ? parsed_locale : nil
  end

  included do
    before_action :set_locale
    before_action :set_content_locale

    def set_locale
      I18n.locale = extract_locale || I18n.default_locale
      Mobility.locale = I18n.locale
    end

    def set_content_locale
      Mobility.locale = extract_locale(:content_locale) || I18n.locale
    end

    def default_url_options
      { locale: I18n.locale, content_locale: Mobility.locale }
    end
  end
end

app/controllers/superheroes_controller.rb
class SuperheroesController < ApplicationController
  before_action :set_superhero, only: [:show, :edit, :update, :destroy]

  # GET /superheroes
  def index
    @superheroes = if params[:name_q]
      Superhero.search params[:name_q]
    else
      Superhero.all
    end
  end

    # Only allow a list of trusted parameters through.
    def superhero_params
      params.require(:superhero).permit(I18n.available_locales.map do |l|
        [:"name_#{Mobility.normalize_locale(l)}", :"description_#{Mobility.normalize_locale(l)}"]
      end.flatten)
    end
    

  # GET /superheroes/1
  def show
  end

  # GET /superheroes/new
  def new
    @superhero = Superhero.new
  end

  # GET /superheroes/1/edit
  def edit
  end

  # POST /superheroes
  def create
    @superhero = Superhero.new(superhero_params)

    if @superhero.save
      redirect_to @superhero, notice: t('.success')
    else
      render :new
    end
  end

  # PATCH/PUT /superheroes/1
  def update
    if @superhero.update(superhero_params)
      redirect_to @superhero, notice: t('.success')
    else
      render :edit
    end
  end

  # DELETE /superheroes/1
  def destroy
    @superhero.destroy
    redirect_to superheroes_url, notice: t('.success')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_superhero
      @superhero = Superhero.find(params[:id])
    end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/superheroes_helper.rb
module SuperheroesHelper
  def all_locales
    I18n.available_locales
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>MobilityDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <ul>
      <li><%= link_to t('main_menu.superheroes'), superheroes_path %></li>
      <li><%= link_to t('main_menu.add_superhero'), new_superhero_path %></li>
    </ul>

    <ul>
      <li><%= link_to 'English', root_path(locale: :en) %></li>
      <li><%= link_to 'Русский', root_path(locale: :ru) %></li>
    </ul>

    <div>
      <%= form_with url: superheroes_path, method: :get do |f| %>
        <%= f.text_field :name_q, value: params[:name_q], placeholder: t('main_menu.search.name'), required: true, minlength: 2 %>
        <%= hidden_field_tag :content_locale, Mobility.locale %>
        <%= f.submit t('global.actions.submit') %>
      <% end %>
    </div>

    <hr>

    <p><%= t 'main_menu.content_locale' %></p>
    <ul>
      <li><%= link_to 'English', root_path(content_locale: :en) %></li>
      <li><%= link_to 'Русский', root_path(content_locale: :ru) %></li>
    </ul>

    <%= yield %>
  </body>
</html>

app/views/superheroes/_form.html.erb
<%= form_with(model: superhero) do |form| %>
  <% if superhero.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% superhero.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% all_locales.each do |locale| %>
    <div class="field">
      <% name = "name_#{Mobility.normalize_locale(locale)}" %>
      <%= form.label name %>
      <%= form.text_field name %>
    </div>

    <div class="field">
      <% description = "description_#{Mobility.normalize_locale(locale)}" %>
      <%= form.label description %>
      <%= form.text_area description %>
    </div>


    <div class="field">
      <% nemesis_ = "nemesis_#{Mobility.normalize_locale(locale)}" %>
      <%= form.label nemesis_ %>
      <%= form.text_area nemesis_ %>
    </div>

    <div class="field">
      <% gadget_ = "gadget_#{Mobility.normalize_locale(locale)}" %>
      <%= form.label gadget_ %>
      <%= form.text_area gadget_ %>
    </div>

    <hr>
  <% end %>

  <div class="actions">
    <%= form.submit t('global.actions.submit') %>
  </div>
<% end %>

app/views/superheroes/_superhero.html.erb
<div id="<%= dom_id superhero %>">
  <p>
    <strong>Name:</strong>
    <%= superhero.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= superhero.description %>
  </p>

  <p>
    <strong>Gadget:</strong>
    <%= superhero.gadget %>
  </p>

<p>
    <strong>Nemesis:</strong>
    <%= superhero.nemesis %>
  </p>
</div>

app/views/superheroes/edit.html.erb
<h1><%= t '.title' %></h1>

<%= render 'form', superhero: @superhero %>

app/views/superheroes/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t '.title' %></h1>

<%= link_to t('.new'), new_superhero_path %>
<br>
<br>
<div>
    <% @superheroes.each do |superhero| %>

        <div id="<%= dom_id superhero %>">
        <%= link_to t('.show'), superhero %>
        <%= link_to t('.edit'), edit_superhero_path(superhero) %>
        <%= link_to t('.destroy'), superhero, method: :delete, data: { confirm: 'Are you sure?' } %>

            <p>
                <strong>Name:</strong>
                <%= superhero.name %>
            </p>
            <p>
                <strong>Description:</strong>
                <%= superhero.description %>
            </p>
            <p>
                <strong>Gadget:</strong>
                <%= superhero.gadget %>
            </p>
            <p>
                <strong>Nemesis:</strong>
                <%= superhero.nemesis %>
            </p>
        </div>
    <% end %>

app/views/superheroes/new.html.erb
<h1><%= t '.title' %></h1>

<%= render 'form', superhero: @superhero %>

app/views/superheroes/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= @superhero.name %>
</h1>

<p>
  <%= @superhero.description %>
</p>

<p>
  <%= @superhero.gadget %>
</p>

<p>
  <%= @superhero.nemesis %>
</p>